### ISSUE TITLE
Problem with getting_started

### ISSUE THREAD

**Issue by sudoer-Huatao** [OpenTechSchool/python-beginners#115]
I am a Mac user, and typing `python` in the console (Mac terminal) doesn't activate the Python Shell (I used the official python.org shell, newest version). But typing `python3` instead DOES work.
<img width="570" alt="截屏2023-08-24 13 07 46" src="https://github.com/OpenTechSchool/python-beginners/assets/135504586/e9f47a60-d850-432c-a868-58f7e0f4d7f0">

Can anybody please clarify for which Mac versions support the `python` command and which versions support `python3` instead? Or is it just because the `python` command in the console is only limited to Python 2 versions?

**Comment by normade** [comment]
@sudoer-Huatao Mac comes usually with the 2 Python versions pre-installed which are not recommended to work with, those are system versions. If you already downloaded a Python version from somewhere it could lead to a mess unfortunately due to different versions on the systems and depending on the path which has been configured. 

Therefore, I highly recommend before you start any projects to learn about `pyenv` a manager to avoid that and handle multiple Python versions on your machine in a clean not-conflicting way. Please have a look for example here: https://realpython.com/intro-to-pyenv/

**Comment by sudoer-Huatao** [comment]
> @sudoer-Huatao Mac comes usually with the 2 Python versions pre-installed which are not recommended to work with, those are system versions. If you already downloaded a Python version from somewhere it could lead to a mess unfortunately due to different versions on the systems and depending on the path which has been configured.
> 
> Therefore, I highly recommend before you start any projects to learn about `pyenv` a manager to avoid that and handle multiple Python versions on your machine in a clean not-conflicting way. Please have a look for example here: https://realpython.com/intro-to-pyenv/

Ok, I think that solves the problem. Thanks a lot! :)
